version: '3.5'
services:
  migrations:
    container_name: moviexprt-migrations
    image: moviexprt-migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on:
        - sqlserver

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123